# Generated by Django 2.0.13 on 2019-03-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('created_date', models.DateField()),
                ('valor', models.DecimalField(decimal_places=3, max_digits=5)),
                ('tipo', models.BooleanField(default=False)),
                ('categoria', models.IntegerField(choices=[(1, 'Alimentação'), (2, 'Cuidados pessoais'), (3, 'Transporte/Combustível/Estacionamento'), (4, 'Água'), (5, 'Luz'), (6, 'Passeios/Viagens'), (7, 'Cinema/Teatro'), (8, 'Farmáciao'), (9, 'Vestuário'), (10, 'Cuidados com animais de estimação')], default=1)),
            ],
        ),
    ]
